# Generated by Django 4.2.1 on 2023-05-16 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='projetos',
        ),
        migrations.AddField(
            model_name='aluno',
            name='projeto',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.projetopesquisa'),
            preserve_default=False,
        ),
    ]
